# Generated by Django 2.0.1 on 2018-01-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180107_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
