# Generated by Django 2.0.1 on 2018-01-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_postimage_related_post'),
    ]

    operations = [
        migrations.RenameField('Comment', 'body', 'comment')
    ]
