# Generated by Django 2.0.1 on 2018-01-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180114_1555'),
    ]

    operations = [
        migrations.RenameField('Comment', 'comment', 'body')
    ]
