# Generated by Django 2.0.1 on 2018-01-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_num_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_comments',
        ),
    ]
