# Generated by Django 2.0.1 on 2018-01-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180117_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postthumbnailimage',
            name='related_post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
