# Generated by Django 2.0.1 on 2018-01-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_num_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
